FROM python:3.9.1

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

ADD ./requirements.txt /usr/src/app/requirements.txt

RUN pip install -r requirements.txt

# add app
ADD . /usr/src/app

EXPOSE 8000
CMD python manage.py makemigrations api & python manage.py migrate api & python manage.py migrate & python manage.py runserver 0.0.0.0:8000